using Microsoft.AspNetCore.Builder;
using Orleans.Caching.Contracts.Grains;
using System.Collections.Immutable;

var builder = WebApplication.CreateBuilder(args);

builder.AddKeyedRedisClient("country-redis");
builder.UseOrleans(siloBuilder =>
{
    //siloBuilder.UseDashboard();
});

// Add service defaults & Aspire client integrations.
builder.AddServiceDefaults();

// Add services to the container.
builder.Services.AddProblemDetails();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

var app = builder.Build();

app.MapDefaultEndpoints();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}
app.UseHttpsRedirection();

app.UseCors(static builder => builder
    .AllowAnyOrigin()
    .AllowAnyMethod()
    .AllowAnyHeader());


// Configure the HTTP request pipeline.
app.UseExceptionHandler();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

string[] summaries = ["Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"];

app.MapGet("/", () => "API service is running. Navigate to /weatherforecast to see sample data.");

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast");

app.MapGet("/countries", async (IGrainFactory factory) =>
{
    var countryGrain = factory.GetGrain<ICountryDetailsGrain>(Guid.NewGuid());
    return await countryGrain.GetCountryAsync();
})
.WithName("GetCountries");

app.MapPost("/cache/{key}", async (IGrainFactory factory, string key, string keyBody, int? ttl) =>
{
    var cacheGrain = factory.GetGrain<ICacheGrain>(key);
    await cacheGrain.Set(keyBody, ttl.HasValue ? TimeSpan.FromSeconds(ttl.Value) : null);
    return Results.Ok();
});

app.MapGet("/cache/{key}", async (IGrainFactory factory, string key) =>
{
    var cacheGrain = factory.GetGrain<ICacheGrain>(key);
    var value = await cacheGrain.Get();
    if (!string.IsNullOrEmpty(value))
    {
        return Results.Ok(value);
    }
    return Results.NotFound();
});

app.MapDefaultEndpoints();

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}

[Immutable]
[GenerateSerializer]
public record class CacheItem(string Key, string Value);


public class CacheGrain : Grain, ICacheGrain
{
    private string _value;
    private DateTime? _ttl;

    public Task Set(string value, TimeSpan? ttl = null)
    {
        _value = value;
        if (ttl.HasValue)
        {
            _ttl = DateTime.UtcNow.Add(ttl.Value);
        }
        return Task.CompletedTask;
    }
    public Task<string> Get()
    {
        if (_ttl.HasValue && DateTime.UtcNow > _ttl.Value)
        {
            return Task.FromResult(string.Empty);
        }

        return Task.FromResult(_value);
    }


}

// Models
[Immutable]
[GenerateSerializer]
public record class CountryDetails(
    string Name,
    string Code,
    int Population);

// Grain Interface
public interface ICountryDetailsGrain : IGrainWithGuidKey
{
    Task<ImmutableArray<CountryDetails>> GetCountryAsync();
}

// Grain
public class CountryDetailsGrain : ICountryDetailsGrain
{


    // Population data is generated by ChatGPT 4o Mini.
    private readonly ImmutableArray<CountryDetails> _data = ImmutableArray.Create<CountryDetails>(
        new("Afghanistan", "AF", 42000000),
        new("Albania", "AL", 2800000),
        new("Algeria", "DZ", 46000000),
        new("Andorra", "AD", 80000),
        new("Angola", "AO", 35000000),
        new("Antigua and Barbuda", "AG", 100000),
        new("Argentina", "AR", 46000000),
        new("Armenia", "AM", 3000000),
        new("Australia", "AU", 26000000),
        new("Austria", "AT", 9000000),
        new("Azerbaijan", "AZ", 10000000),
        new("Bahamas", "BS", 400000),
        new("Bahrain", "BH", 1700000),
        new("Bangladesh", "BD", 170000000),
        new("Barbados", "BB", 300000),
        new("Belarus", "BY", 9400000),
        new("Belgium", "BE", 11500000),
        new("Belize", "BZ", 500000),
        new("Benin", "BJ", 12000000),
        new("Bhutan", "BT", 800000),
        new("Bolivia", "BO", 12000000),
        new("Bosnia and Herzegovina", "BA", 3300000),
        new("Botswana", "BW", 2500000),
        new("Brazil", "BR", 215000000),
        new("Brunei", "BN", 450000),
        new("Bulgaria", "BG", 6900000),
        new("Burkina Faso", "BF", 22000000),
        new("Burundi", "BI", 13000000),
        new("Cabo Verde", "CV", 600000),
        new("Cambodia", "KH", 18000000),
        new("Cameroon", "CM", 30000000),
        new("Canada", "CA", 40000000),
        new("Central African Republic", "CF", 5000000),
        new("Chad", "TD", 18000000),
        new("Chile", "CL", 20000000),
        new("China", "CN", 1400000000),
        new("Colombia", "CO", 53000000),
        new("Comoros", "KM", 800000),
        new("Congo, Democratic Republic", "CD", 95000000),
        new("Congo, Republic of the", "CG", 5000000),
        new("Costa Rica", "CR", 5000000),
        new("Croatia", "HR", 4000000),
        new("Cuba", "CU", 11000000),
        new("Cyprus", "CY", 1200000),
        new("Czech Republic", "CZ", 11000000),
        new("Denmark", "DK", 6000000),
        new("Djibouti", "DJ", 1000000),
        new("Dominica", "DM", 75000),
        new("Dominican Republic", "DO", 11000000),
        new("East Timor", "EM", 1500000),
        new("Ecuador", "EC", 19000000),
        new("Egypt", "EG", 110000000),
        new("El Salvador", "SV", 7000000),
        new("Equatorial Guinea", "GQ", 1700000),
        new("Eritrea", "ER", 6000000),
        new("Estonia", "EE", 1300000),
        new("Eswatini", "SZ", 1200000),
        new("Ethiopia", "ET", 120000000),
        new("Fiji", "FJ", 950000),
        new("Finland", "FI", 5500000),
        new("France", "FR", 68000000),
        new("Gabon", "GA", 2500000),
        new("Gambia", "GM", 2600000),
        new("Georgia", "GE", 3700000),
        new("Germany", "DE", 83000000),
        new("Ghana", "GH", 35000000),
        new("Greece", "GR", 10000000),
        new("Grenada", "GD", 110000),
        new("Guatemala", "GT", 20000000),
        new("Guinea", "GN", 14000000),
        new("Guinea-Bissau", "GW", 2000000),
        new("Guyana", "GY", 800000),
        new("Haiti", "HT", 12000000),
        new("Honduras", "HN", 11000000),
        new("Hungary", "HU", 9600000),
        new("Iceland", "IS", 400000),
        new("India", "IN", 1500000000),
        new("Indonesia", "ID", 275000000),
        new("Iran", "IR", 90000000),
        new("Iraq", "IQ", 45000000),
        new("Ireland", "IE", 5200000),
        new("Israel", "IL", 9000000),
        new("Italy", "IT", 59000000),
        new("Jamaica", "JM", 3000000),
        new("Japan", "JP", 123000000),
        new("Jordan", "JO", 11000000),
        new("Kazakhstan", "KZ", 20000000),
        new("Kenya", "KE", 58000000),
        new("Kiribati", "KI", 120000),
        new("Korea, North", "KP", 26000000),
        new("Korea, South", "KR", 52000000),
        new("Kosovo", "XK", 2000000),
        new("Kuwait", "KW", 4300000),
        new("Kyrgyzstan", "KG", 6000000),
        new("Laos", "LA", 8000000),
        new("Latvia", "LV", 1900000),
        new("Lebanon", "LB", 7000000),
        new("Lesotho", "LS", 2300000),
        new("Liberia", "LR", 5500000),
        new("Libya", "LY", 7000000),
        new("Liechtenstein", "LI", 40000),
        new("Lithuania", "LT", 2700000),
        new("Luxembourg", "LU", 700000),
        new("Madagascar", "MG", 30000000),
        new("Malawi", "MW", 22000000),
        new("Malaysia", "MY", 34000000),
        new("Maldives", "MV", 550000),
        new("Mali", "ML", 21000000),
        new("Malta", "MT", 530000),
        new("Marshall Islands", "MH", 60000),
        new("Mauritania", "MR", 4800000),
        new("Mauritius", "MU", 1300000),
        new("Mexico", "MX", 130000000),
        new("Micronesia", "FM", 120000),
        new("Moldova", "MD", 2600000),
        new("Monaco", "MC", 40000),
        new("Mongolia", "MN", 3500000),
        new("Montenegro", "ME", 700000),
        new("Morocco", "MA", 37000000),
        new("Mozambique", "MZ", 35000000),
        new("Myanmar", "MM", 56000000),
        new("Namibia", "NA", 2500000),
        new("Nauru", "NR", 11000),
        new("Nepal", "NP", 30000000),
        new("Netherlands", "NL", 18000000),
        new("New Zealand", "NZ", 5000000),
        new("Nicaragua", "NI", 7000000),
        new("Niger", "NE", 26000000),
        new("Nigeria", "NG", 230000000),
        new("North Macedonia", "MK", 2100000),
        new("Norway", "NO", 5700000),
        new("Oman", "OM", 5100000),
        new("Pakistan", "PK", 240000000),
        new("Palau", "PW", 18000),
        new("Panama", "PA", 4500000),
        new("Papua New Guinea", "PG", 9000000),
        new("Paraguay", "PY", 7200000),
        new("Peru", "PE", 35000000),
        new("Philippines", "PH", 115000000),
        new("Poland", "PL", 38000000),
        new("Portugal", "PT", 10000000),
        new("Qatar", "QA", 2900000),
        new("Romania", "RO", 19000000),
        new("Russia", "RU", 145000000),
        new("Rwanda", "RW", 13000000),
        new("Saint Kitts and Nevis", "KN", 55000),
        new("Saint Lucia", "LC", 200000),
        new("Saint Vincent and the Grenadines", "VC", 110000),
        new("Samoa", "WS", 200000),
        new("San Marino", "SM", 35000),
        new("Sao Tome and Principe", "ST", 220000),
        new("Saudi Arabia", "SA", 37000000),
        new("Senegal", "SN", 17000000),
        new("Serbia", "RS", 7000000),
        new("Seychelles", "SC", 100000),
        new("Sierra Leone", "SL", 8000000),
        new("Singapore", "SG", 5800000),
        new("Slovakia", "SK", 5400000),
        new("Slovenia", "SI", 2100000),
        new("Solomon Islands", "SB", 800000),
        new("Somalia", "SO", 16000000),
        new("South Africa", "ZA", 61000000),
        new("South Sudan", "SS", 12000000),
        new("Spain", "ES", 47000000),
        new("Sri Lanka", "LK", 22000000),
        new("Sudan", "SD", 46000000),
        new("Suriname", "SR", 600000),
        new("Sweden", "SE", 10500000),
        new("Switzerland", "CH", 8700000),
        new("Syria", "SY", 19000000),
        new("Taiwan", "TW", 24000000),
        new("Tajikistan", "TJ", 9500000),
        new("Tanzania", "TZ", 64000000),
        new("Thailand", "TH", 70000000),
        new("Timor-Leste", "TL", 1500000),
        new("Togo", "TG", 8500000),
        new("Tonga", "TO", 100000),
        new("Trinidad and Tobago", "TT", 1400000),
        new("Tunisia", "TN", 12000000),
        new("Turkey", "TR", 88000000),
        new("Turkmenistan", "TM", 6300000),
        new("Tuvalu", "TV", 11000),
        new("Uganda", "UG", 46000000),
        new("Ukraine", "UA", 41000000),
        new("United Arab Emirates", "AE", 9000000),
        new("United Kingdom", "GB", 68000000),
        new("United States", "US", 340000000),
        new("Uruguay", "UY", 3500000),
        new("Uzbekistan", "UZ", 35000000),
        new("Vanuatu", "VU", 320000),
        new("Vatican City", "VA", 800),
        new("Venezuela", "VE", 34000000),
        new("Vietnam", "VN", 98000000),
        new("Yemen", "YE", 33000000),
        new("Zambia", "ZM", 19000000),
        new("Zimbabwe", "ZW", 17000000));

    public Task<ImmutableArray<CountryDetails>> GetCountryAsync() => Task.FromResult(_data);
}